# version: "3.8"
services:
  user-service:
    build: ./serviceB
    container_name: serviceB
    ports:
      - "3001:3001"
    networks:
      - my-network

  post-service:
    build: ./serviceA
    container_name: serviceA
    ports:
      - "3002:3002"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - serviceB
      - serviceA
    networks:
      - my-network

networks:
  my-network:
